/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tamagotchi.letsdev.ui;

import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import static javax.swing.JOptionPane.ERROR_MESSAGE;
import javax.swing.*;
import tamagotchi.letsdev.database.Requeteur;
import tamagotchi.letsdev.etat.GestionEtats;
import tamagotchi.letsdev.objets.*;
import tamagotchi.letsdev.tamagotchi.*;

/**
 *
 * @author Nicolas
 */
public class Fenetre extends javax.swing.JFrame {
    
    private ActionsBoutons actions;
    private List<JButton> boutons;
    private List<Item> items;
    private List<Race> races;
    private Tamagotchi tama;
    private GestionEtats gestEtats;
    
    /**
     * Creates new form Fenetre
     */
    public Fenetre() {
        initComponents();
        initFenetre();
        initFromBDD();
        loadData();
        
        setVisible(true);
        actions = new ActionsBoutons(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

                jPanelEtats = new javax.swing.JPanel();
                jLabel1 = new javax.swing.JLabel();
                jProgressBarFaim = new javax.swing.JProgressBar();
                jLabel2 = new javax.swing.JLabel();
                jLabel3 = new javax.swing.JLabel();
                jLabel4 = new javax.swing.JLabel();
                jProgressBarSoif = new javax.swing.JProgressBar();
                jProgressBarEnnui = new javax.swing.JProgressBar();
                jProgressBarFatigue = new javax.swing.JProgressBar();
                jPanelMenu = new javax.swing.JPanel();
                jPanel4 = new javax.swing.JPanel();
                jButtonNourrir = new javax.swing.JButton();
                jButtonDormir = new javax.swing.JButton();
                jButtonExplorer = new javax.swing.JButton();
                jButtonSauver = new javax.swing.JButton();
                jPanel2 = new javax.swing.JPanel();
                jButtonCaliner = new javax.swing.JButton();
                jButtonJouer = new javax.swing.JButton();
                jLabel5 = new javax.swing.JLabel();
                jLabelScore = new javax.swing.JLabel();
                jLayeredPane1 = new javax.swing.JLayeredPane();
                jPanelJeuFond = new javax.swing.JPanel();
                jLabelInfoJeu = new javax.swing.JLabel();
                jLabelImageJeu = new javax.swing.JLabel();

                setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
                setTitle("Tamagotchi !");
                setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
                setFocusable(false);
                setMaximumSize(new java.awt.Dimension(600, 600));
                setMinimumSize(new java.awt.Dimension(440, 440));
                setResizable(false);

                jPanelEtats.setBackground(new java.awt.Color(250, 250, 250));
                jPanelEtats.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

                jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
                jLabel1.setText("Faim");

                jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
                jLabel2.setText("Soif");

                jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
                jLabel3.setText("Ennui");

                jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
                jLabel4.setText("Fatigue");

                javax.swing.GroupLayout jPanelEtatsLayout = new javax.swing.GroupLayout(jPanelEtats);
                jPanelEtats.setLayout(jPanelEtatsLayout);
                jPanelEtatsLayout.setHorizontalGroup(
                        jPanelEtatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelEtatsLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanelEtatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanelEtatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jProgressBarFaim, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                                        .addComponent(jProgressBarSoif, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jProgressBarEnnui, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jProgressBarFatigue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap())
                );
                jPanelEtatsLayout.setVerticalGroup(
                        jPanelEtatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelEtatsLayout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanelEtatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jProgressBarFaim, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanelEtatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jProgressBarSoif, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanelEtatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jProgressBarEnnui, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanelEtatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jProgressBarFatigue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap())
                );

        jButtonNourrir.setText("Nourrir");
        jButtonNourrir.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButtonNourrirActionPerformed(evt);
            }
        });

                jButtonDormir.setText("Dormir");

                jButtonExplorer.setText("Explorer");

                jButtonSauver.setText("Sauver");

                javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
                jPanel4.setLayout(jPanel4Layout);
                jPanel4Layout.setHorizontalGroup(
                        jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jButtonNourrir, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(220, 220, 220)
                                        .addComponent(jButtonSauver, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jButtonDormir, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(10, 10, 10)
                                        .addComponent(jButtonExplorer, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                );
                jPanel4Layout.setVerticalGroup(
                        jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jButtonNourrir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonSauver, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jButtonExplorer, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButtonDormir, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                );

                jButtonCaliner.setText("Câliner");
                jButtonCaliner.setMaximumSize(new java.awt.Dimension(95, 35));
                jButtonCaliner.setMinimumSize(new java.awt.Dimension(95, 35));
                jButtonCaliner.setPreferredSize(new java.awt.Dimension(95, 35));

                jButtonJouer.setText("Jouer");

                jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
                jLabel5.setText("Amitié :");

                jLabelScore.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

                javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
                jPanel2.setLayout(jPanel2Layout);
                jPanel2Layout.setHorizontalGroup(
                        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jButtonCaliner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelScore, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonJouer, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                );
                jPanel2Layout.setVerticalGroup(
                        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jButtonCaliner, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButtonJouer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabelScore, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(0, 0, Short.MAX_VALUE))
                );

                javax.swing.GroupLayout jPanelMenuLayout = new javax.swing.GroupLayout(jPanelMenu);
                jPanelMenu.setLayout(jPanelMenuLayout);
                jPanelMenuLayout.setHorizontalGroup(
                        jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelMenuLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanelMenuLayout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap())
                );
                jPanelMenuLayout.setVerticalGroup(
                        jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelMenuLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );

                jPanelJeuFond.setBackground(new java.awt.Color(245, 245, 245));
                jPanelJeuFond.setPreferredSize(new java.awt.Dimension(410, 185));

                javax.swing.GroupLayout jPanelJeuFondLayout = new javax.swing.GroupLayout(jPanelJeuFond);
                jPanelJeuFond.setLayout(jPanelJeuFondLayout);
                jPanelJeuFondLayout.setHorizontalGroup(
                        jPanelJeuFondLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 410, Short.MAX_VALUE)
                );
                jPanelJeuFondLayout.setVerticalGroup(
                        jPanelJeuFondLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 185, Short.MAX_VALUE)
                );

                jLabelInfoJeu.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
                jLabelInfoJeu.setText("Some text goes here!");

                jLabelImageJeu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                jLabelImageJeu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/baudrive.png"))); // NOI18N
                jLabelImageJeu.setMaximumSize(new java.awt.Dimension(410, 185));
                jLabelImageJeu.setMinimumSize(new java.awt.Dimension(410, 185));
                jLabelImageJeu.setPreferredSize(new java.awt.Dimension(410, 185));

                javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
                jLayeredPane1.setLayout(jLayeredPane1Layout);
                jLayeredPane1Layout.setHorizontalGroup(
                        jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(jLabelInfoJeu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(jPanelJeuFond, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addContainerGap()))
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(jLabelImageJeu, javax.swing.GroupLayout.DEFAULT_SIZE, 410, Short.MAX_VALUE)
                                        .addContainerGap()))
                );
                jLayeredPane1Layout.setVerticalGroup(
                        jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                                .addContainerGap(169, Short.MAX_VALUE)
                                .addComponent(jLabelInfoJeu, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(19, 19, 19))
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addComponent(jPanelJeuFond, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(jLabelImageJeu, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                                        .addGap(12, 12, 12)))
                );
                jLayeredPane1.setLayer(jPanelJeuFond, 1);
                jLayeredPane1.setLayer(jLabelInfoJeu, javax.swing.JLayeredPane.POPUP_LAYER);
                jLayeredPane1.setLayer(jLabelImageJeu, javax.swing.JLayeredPane.PALETTE_LAYER);

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanelMenu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanelEtats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(63, 63, 63))
                        .addComponent(jLayeredPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanelMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jPanelEtats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30))
                );

                pack();
        }// </editor-fold>//GEN-END:initComponents

    private void jButtonNourrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNourrirActionPerformed
        actions.nourrir();
    }//GEN-LAST:event_jButtonNourrirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Fenetre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Fenetre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Fenetre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Fenetre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Fenetre().setVisible(true);
            }
        });
    }

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton jButtonCaliner;
        private javax.swing.JButton jButtonDormir;
        private javax.swing.JButton jButtonExplorer;
        private javax.swing.JButton jButtonJouer;
        private javax.swing.JButton jButtonNourrir;
        private javax.swing.JButton jButtonSauver;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLabel3;
        private javax.swing.JLabel jLabel4;
        private javax.swing.JLabel jLabel5;
        private javax.swing.JLabel jLabelImageJeu;
        private javax.swing.JLabel jLabelInfoJeu;
        private javax.swing.JLabel jLabelScore;
        private javax.swing.JLayeredPane jLayeredPane1;
        private javax.swing.JPanel jPanel2;
        private javax.swing.JPanel jPanel4;
        private javax.swing.JPanel jPanelEtats;
        private javax.swing.JPanel jPanelJeuFond;
        private javax.swing.JPanel jPanelMenu;
        private javax.swing.JProgressBar jProgressBarEnnui;
        private javax.swing.JProgressBar jProgressBarFaim;
        private javax.swing.JProgressBar jProgressBarFatigue;
        private javax.swing.JProgressBar jProgressBarSoif;
        // End of variables declaration//GEN-END:variables

    private void initFenetre() {
        setLocationRelativeTo(null);
        
        boutons = new ArrayList<>();
        boutons.add(jButtonCaliner);
        boutons.add(jButtonDormir);
        boutons.add(jButtonExplorer);
        boutons.add(jButtonJouer);
        boutons.add(jButtonNourrir);
        boutons.add(jButtonSauver);
    }
    
    
    public boolean griserBoutons(boolean bool) {
        for(JButton jb: boutons) {
            jb.setEnabled(!bool);
        }
        
        return true;
    }
    
    public int ajouterScore(int nb) {
        int current = Integer.parseInt(jLabelScore.getText());
        int updated = current + nb;
        
        jLabelScore.setText("" + updated);
        
        return getScore();
    }
    
    public int getScore() {
        
        return tama.getAmitie();
    }

    private void initFromBDD() {
        try {
            Requeteur rq = new Requeteur();
            
            items = rq.getItems();
            races = rq.getRaces();
            
        } catch (ClassNotFoundException ex) {
            showError("Erreur base de données", "Le pilote Derby n'est pas disponible.");
        } catch (SQLException ex) {
            showError("Erreur base de données", "Une erreur SQL n°"+ex.getErrorCode()+" s'est produite.");
        }
    }
    
    private void showError(String titre, Object text) {
        JOptionPane.showMessageDialog(null, text, titre, ERROR_MESSAGE);
        this.dispose();
    }

    public List<Item> getItems() {
        return items;
    }

    public List<Race> getRaces() {
        return races;
    }

    private void loadData() {
        // code pour charger les données.
        
        // TODO gereretats : creer
        boolean existant = false;
        if(existant) {
            // TODO ; Charger
            // TODO gererEtats activer
            
            setTitle(getTitle()+" "+tama.getNom());
            
        } else {
        
            // si aucune save :
            griserBoutons(true);
            tama = new Tamagotchi(races);


            JLabel nameAsk = new JLabel("Nom :");
            JTextField nameArea = new JTextField();
            JButton nameConfirm = new JButton("OK");

            jLayeredPane1.add(nameAsk);
            jLayeredPane1.add(nameArea);
            jLayeredPane1.add(nameConfirm);
            jLayeredPane1.setLayer(nameAsk,     1000);
            jLayeredPane1.setLayer(nameArea,    1000);
            jLayeredPane1.setLayer(nameConfirm, 1000);
            nameAsk.setSize(100, 20);
            nameArea.setSize(100, 20);
            nameConfirm.setSize(60, 19);
            nameAsk.setLocation(100, 50);
            nameArea.setLocation(150, 50);
            nameConfirm.setLocation(250, 50);

            class LocalListener implements ActionListener {

                @Override
                public void actionPerformed(ActionEvent e) {
                    tama.setNom(nameArea.getText());
                    griserBoutons(false);

                    setTitle(getTitle()+" "+tama.getNom());

                    jLayeredPane1.remove(nameAsk);
                    jLayeredPane1.remove(nameArea);
                    jLayeredPane1.remove(nameConfirm);

                    jLayeredPane1.validate();
                    jLayeredPane1.repaint();
                    // TODO : gererEtats.activer
                }

            }

            nameConfirm.addActionListener(new LocalListener());

        }
        
        // après :
        jLabelScore.setText(String.valueOf(tama.getAmitie()));
        String img = tama.getRace().getImage();
        
        if(new File(getClass().getResource(img).getPath()).isFile()) {
            
            if(!img.isEmpty()) {
                ImageIcon image = new ImageIcon(getClass().getResource(img));

                boolean tropLarge = image.getIconWidth() > jLabelImageJeu.getWidth();
                boolean tropGrand = image.getIconHeight() > jLabelImageJeu.getHeight();


                if(tropLarge) {
                    image = new ImageIcon(image.getImage().getScaledInstance(jLabelImageJeu.getWidth(), -1, Image.SCALE_DEFAULT));
                }
                if(tropGrand) {
                    image = new ImageIcon(image.getImage().getScaledInstance(-1, jLabelImageJeu.getHeight(), Image.SCALE_SMOOTH));
                }

                jLabelImageJeu.setIcon(image);
            }
            
        } else {
            System.out.println("IMAGE PAS OK : "+getClass().getResource(img).getPath());
        }
        
        
    }

    public Tamagotchi getTamagotchi() {
        return tama;
    }

    public JProgressBar getjProgressBarEnnui() {
        return jProgressBarEnnui;
    }

    public JProgressBar getjProgressBarFaim() {
        return jProgressBarFaim;
    }

    public JProgressBar getjProgressBarFatigue() {
        return jProgressBarFatigue;
    }

    public JProgressBar getjProgressBarSoif() {
        return jProgressBarSoif;
    }
}
